output "state_bucket_name" {
  description = "Name of the S3 bucket that stores Terraform remote state"
  value       = aws_s3_bucket.terraform_state.bucket
}

output "state_bucket_arn" {
  description = "ARN of the Terraform state S3 bucket"
  value       = aws_s3_bucket.terraform_state.arn
}

output "dynamodb_table_name" {
  description = "Name of the DynamoDB table used for state locking"
  value       = aws_dynamodb_table.terraform_locks.name
}

output "dynamodb_table_arn" {
  description = "ARN of the DynamoDB locking table"
  value       = aws_dynamodb_table.terraform_locks.arn
}

output "aws_account_id" {
  description = "AWS account ID — needed when constructing the backend.hcl for the infra workspace"
  value       = data.aws_caller_identity.current.account_id
}

output "backend_hcl_snippet" {
  description = "Copy-paste this into infra/backend.hcl (replacing the placeholder)"
  value       = <<-EOT

    # infra/backend.hcl — generated by bootstrap outputs
    bucket         = "${aws_s3_bucket.terraform_state.bucket}"
    key            = "infra/terraform.tfstate"
    region         = "${var.aws_region}"
    dynamodb_table = "${aws_dynamodb_table.terraform_locks.name}"
    encrypt        = true
  EOT
}
